name: clustering
channels:
  - conda-forge
dependencies:
  - python=3.8
  - ipykernel
  - scipy
  - numpy
  - matplotlib
  - pandas
  - pandas-datareader>=0.8.1
  - geopandas
  - geopy
  - unidecode
  - simplekml
  - folium
  - pip
  - pip:
  - pip
  - pip:
    - voila>=0.1.21
    - voila-material
    - voila-gridstack
    - ipywidgets>=7.5.1
    - bqplot>=0.11.2
    - ipysheet>=0.4.4
    - pyroutelib3
    - tsp_solver2
