name: clustering
channels:
  - conda-forge
dependencies:
  - bqplot=0.11.2
  - ipykernel
  - voila
  - scipy
  - numpy
  - matplotlib
  - pandas
  - pandas-datareader>=0.8.1
  - geopandas
  - geopy
  - unidecode
  - simplekml
  - folium
  - pip
  - pip:
    - pyroutelib3
    - tsp_solver2
    - qgrid>=1.3.0
